### ISSUE TITLE
Bug when entering factories from factorissimo 3.3.12

### ISSUE THREAD

**Issue by BlueCroco26** [Pikachar2/PersonalTransformer#25]
The game displays this error upon entering the factorissimo buildings:

The mod Personal Transformer2 (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event PersonalTransformer2::on_player_changed_surface (ID 54)
Unknown quality name: legendary
stack traceback:
	[C]: in function 'create_entity'
	__PersonalTransformer2__/control.lua:566: in function 'insert_entity'
	__PersonalTransformer2__/control.lua:781: in function 'equipmentInserted'
	__PersonalTransformer2__/control.lua:874: in function 'playerOrArmorChanged'
	__PersonalTransformer2__/control.lua:285: in function <__PersonalTransformer2__/control.lua:281>

**Comment by BlueCroco26** [comment]
getting this error when equiping an armor with the transformers inside it:
The mod Personal Transformer2 (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event PersonalTransformer2::on_player_armor_inventory_changed (ID 38)
Unknown quality name: legendary
stack traceback:
	[C]: in function 'create_entity'
	__PersonalTransformer2__/control.lua:566: in function 'insert_entity'
	__PersonalTransformer2__/control.lua:781: in function 'equipmentInserted'
	__PersonalTransformer2__/control.lua:874: in function 'playerOrArmorChanged'
	__PersonalTransformer2__/control.lua:174: in function <__PersonalTransformer2__/control.lua:172>

**Comment by Pikachar2** [comment]
My bad, forgot to run tests with quality disabled. Should be fixed in 1.0.5
